Prueba_4/urls.py
from django.contrib import admin
from django.urls import path
from Prueba_4.views.home import v_index
from Prueba_4.views.galeria import v_galeria
from Prueba_4.views.contacto import contacto_index, formulario_contacto
from Prueba_4.views import login
from Prueba_4.views import logout
from Prueba_4.views.mantenedorcontacto import load_contacto
from django.contrib.auth.models import Permission, ContentType
from Prueba_4.models import Contacto
from Prueba_4.views import errorpage
from Prueba_4.api.v1 import apiv1
from Prueba_4.views.tienda import v_tienda

admin.site.register(Permission)
admin.site.register(ContentType)
admin.site.register(Contacto)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', v_index),
    path('', v_index),
    path('galeria/', v_galeria),
    path('contacto/', contacto_index),
    path('contacto/formulario', formulario_contacto),
    path('mantenedor-contacto/', load_contacto),
    path('login', login.index),  
    path('logout/', logout.logout_user),
    path('error-401/', errorpage.error_401_page),
    path('error-403/', errorpage.error_403_page),
    path('api/v1/contacto', apiv1.contacto),
    path('tienda/', v_tienda),
]

Prueba_4/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Contacto(models.Model):
    codigo = models.BigAutoField(primary_key=True)
    run = models.DecimalField(max_digits=13, decimal_places=0, blank=True, null=True)
    dv = models.CharField(max_length=1, blank=True, null=True)
    nombres = models.CharField(max_length=80, blank=True, null=True)
    apellido_paterno = models.CharField(max_length=80, blank=True, null=True)
    apellido_materno = models.CharField(max_length=80, blank=True, null=True)
    email = models.CharField(max_length=80, blank=True, null=True)
    telefono = models.CharField(max_length=16, blank=True, null=True)
    asunto = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'contacto'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

Prueba_4/views/contacto.py
from django.shortcuts import render
from Prueba_4.models import Contacto

def contacto_index(request):
    print('contacto_index')
    return render(request, 'contact.html')

def formulario_contacto(request):
    print('formulario_contacto')

    if request.method == 'GET':
        print('invocación por método GET')
        run = request.GET.get('run')
        print('run {0}'.format(run))

    elif request.method == 'POST':
        print('invocación por método POST')
        #obtener información formulario
        #almacenandola en variables
        run = request.POST.get('run')
        dv = request.POST.get('dv')
        nombres = request.POST.get('nombres')
        apellido_paterno = request.POST.get('apellido-paterno')
        apellido_materno = request.POST.get('apellido-materno')
        email = request.POST.get('email')
        telefono = request.POST.get('telefono')
        asunto = request.POST.get('asunto')
        #Crear un objecto Contacto
        #que posee relación con la tabla contacto
        contacto = Contacto()
        contacto.run = run
        contacto.dv = dv
        contacto.nombres = nombres
        contacto.apellido_paterno = apellido_paterno
        contacto.apellido_materno = apellido_materno
        contacto.email = email
        contacto.telefono = telefono
        contacto.asunto = asunto
        contacto.save()
    return render(request, 'contact.html')

Prueba_4/views/errorpage.py
from django.shortcuts import render

def error_401_page(request):
    return render(request, 'error-401.html')

def error_403_page(request):
    return render(request, 'error-403.html')

Prueba_4/views/galeria.py
import requests
from django.shortcuts import render

def v_galeria(request):
    print("Llevando a gallery.html")
    return render(request, 'gallery.html')

Prueba_4/views/home.py
from django.shortcuts import render

def v_index(request):
    print("Llevando a index.html")
    return render(request, 'index.html')

Prueba_4/views/login.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate

def index(request):
    print('login.index')
    if request.method == 'POST':
        print('request.method: ',  request.method)        
        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            print('username: ',  username)        
            print('password: ',  password)                    
            user = authenticate(username=username, password=password)
            print('authenticated: ',  True)                                            
            login(request, user)
            print('login: ',  True)                                
            return redirect('/index/')
        except Exception as e:
            print(e)        
    return render(request, 'login.html')

def authorization(request, perm):
    print('authorization | user -> ', request.user)
    if request.user != None and request.user.__str__() != 'AnonymousUser':
        if request.user.has_perm(perm):
            return True, ''
        else:
            return False, '/error-403/'
    else:
        print('Unauthorized')
        return False, '/error-401/'

Prueba_4/views/logout.py
from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_user(request):
    print('logout')
    try:
        logout(request)
    except Exception as e:
        print('Error: ', e)
    return redirect('/index/')

Prueba_4/views/mantenedorcontacto.py
from django.shortcuts import render, redirect
from Prueba_4.models import Contacto
from Prueba_4.views.login import authorization

def load_contacto(request):
    print('mantenedorcontacto.py -> load_contacto')    
    print('method -> ', request.method)
    if request.method == 'GET':
        try:
            auth, error = authorization(request, 'delete_contacto')
            if not auth:
                redirect(error)
            codigo = request.GET['codigo']
            print('codigo -> ', codigo)
            contacto = Contacto.objects.get(pk=codigo)
            contacto.delete()
        except Exception as e:
            print(e)
    if request.method == 'POST':
        try:
            #Lectura Formulario
            id = request.POST['codigo']
            nombres = request.POST['nombres']
            apellido_paterno = request.POST['apellido_paterno']
            apellido_materno = request.POST['apellido_materno']
            email = request.POST['email']
            telefono = request.POST['telefono']            
            asunto = request.POST['asunto']
            #Busqueda de objecto en la base de datos
            contacto = Contacto.objects.get(pk=id)
            #Actualizando objeto en memoria volatil
            contacto.nombres = nombres
            contacto.apellido_paterno = apellido_paterno
            contacto.apellido_materno = apellido_materno            
            contacto.email = email            
            contacto.telefono = telefono            
            contacto.asunto = asunto  
            #Actualizando en la base de datos                      
            contacto.save(force_update=True)
        except Exception as e:
            print(e)
    contactos = Contacto.objects.all
    return render(request, 'mantenedor-contacto.html', {'contactos': contactos})            
        

Prueba_4/views/tienda.py
import requests
from django.shortcuts import render

def v_tienda(request):
    print("Llevando a tienda.html")
    return render(request, 'tienda.html')

Prueba_4/templates/contact.html
{% extends "template.html" %}
{% load static %}
{% block title %}Contacto{% endblock %}
{% block content %}
<form id="frm-contacto" method="POST" action="/contacto/formulario">{% csrf_token %}
  <div class="container" style="max-width:700px !important">
    <div class="form-group row">
      <div class="col-sm-9">
        <label for="txt-run" class="form-label">RUN</label>
        <input id="txt-run" name="run" class="form-control" placeholder="RUN" />
      </div>
      <div class="col-sm-3">
        <label for="txt-dv" class="form-label">DV</label>
        <input id="txt-dv" name="dv" class="form-control" placeholder="DV" />
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-6">
        <label for="txt-nombres" class="form-label">NOMBRES</label>
        <input id="txt-nombres" name="nombres" class="form-control" placeholder="NOMBRES" />
      </div>
      <div class="col-sm-6">
        <label for="txt-apellido-paterno" class="form-label">APELLIDO PATERNO</label>
        <input id="txt-apellido-paterno" name="apellido-paterno" class="form-control" placeholder="APELLIDO PATERNO" />
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-6">
        <label for="txt-apellido-materno" class="form-label">APELLIDO MATERNO</label>
        <input id="txt-apellido-materno" name="apellido-materno" class="form-control" placeholder="APELLIDO MATERNO" />
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-6">
        <label for="txt-email" class="form-label">EMAIL</label>
        <input type="email" id="txt-email" name="email" class="form-control" placeholder="EMAIL" required pattern="[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{1,5}" />
      </div>
      <div class="col-sm-6">
        <label for="txt-telefono" class="form-label">TELÉFONO</label>
        <input type="tel" id="txt-telefono" name="telefono" class="form-control" placeholder="TELÉFONO" pattern="[0-9]{9}"/>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-12">
        <label for="txt-asunto" class="form-label">ASUNTO</label>
        <textarea id="txt-asunto" name="asunto" class="form-control"></textarea>
      </div>
    </div>
    <div class="form-group row">
      <button type="button" style="margin-top: 15px;" class=" col-sm-3 btn btn-primary"
        onclick="enviar()">ENVIAR</button>
    </div>
  </div>
</form>
<div id="txt-message">
</div>
<div class="container">
  <div class="row justify-content-center mt-3">
    <iframe title="direccion"
    src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1439.1327369467663!2d-70.65700379449123!3d-33.44727071850238!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c508033e91c1%3A0x7de8e2dc07c5ff2a!2sPadre%20Alonso%20de%20Ovalle%201480%2C%20Santiago%2C%20Regi%C3%B3n%20Metropolitana!5e1!3m2!1ses!2scl!4v1656208055355!5m2!1ses!2scl"
    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
    referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
</div>
<div>
  <div class="text-left mt-5 ms-5">
    <h4>Desarrolladores</h4>
    <a href="/api/v1/contacto">Obtén los datos de los desarrolladores aquí.</a>
  </div>
</div>
<script src="{% static 'js/custom/form-enviar-asunto.js' %}"></script>
{% endblock %}

Prueba_4/templates/error-401.html
{% extends "template.html" %}
{% load static %}
{% block title %}Error 401{% endblock %}
{% block content %}
    <h1>401 Unauthorized</h1>
{% endblock %}

Prueba_4/templates/error-403.html
{% extends "template.html" %}
{% load static %}
{% block title %}Error 403{% endblock %}
{% block content %}
    <h1>403 Forbbiden</h1>
{% endblock %}

Prueba_4/templates/gallery.html
{% extends "template.html" %}
{% load static %}
{% block title %}Galería{% endblock %}
{% block content %}
    <div class="text-center">
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'img/tienda.jpg' %}" class="rounded float-left mt-5" width="500px" alt="...">
            </div>
            <div class="col-md-6">
                <img src="{% static 'img/interior3.jpg' %}" width="500px" class="rounded float-right mt-5" alt="...">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'img/interior4.jpg' %}" class="rounded float-left" width="500px" alt="...">
            </div>
            <div class="col-md-6">
                <img src="{% static 'img/interior5.jpg' %}" width="500px" class="rounded float-right mt-5" alt="...">
            </div>
        </div>
    </div>
{% endblock %}

Prueba_4/templates/index.html
{% extends "template.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
<div style="width: 90%; margin:0 auto;" id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/exterior.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>PetShop, ¡siempre con tus mascotas!</h5>
                
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/interior.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Consigue lo mejor para los pequeños de la casa!</h5>
                
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/animales.jpeg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Porque son importantes para nosotros!</h5>
                
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div>
    {% endblock %}

Prueba_4/templates/login.html
{% extends "template.html" %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<form id="frm-login" method="POST" action="/login">{% csrf_token %}
    <div class="container" style="max-width:700px !important">
      <div class="form-group row">
        <div class="col-sm-12">
          <label for="txt-username" class="form-label">USERNAME</label>
          <input id="txt-username" name="username" class="form-control" placeholder="username" required />
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-12">
          <label for="txt-password" class="form-label">PASSWORD</label>
          <input type="password" id="txt-password" name="password" class="form-control" placeholder="password" required/>        
        </div>  
      </div>

      <div class="form-group row">        
          <button type="submit" style="margin-top: 15px;" 
                        class=" col-sm-3 btn btn-primary">LOGIN</button>
      </div>         
    </div>
  </form>    
{% endblock %}

Prueba_4/templates/mantenedor-contacto.html
{% extends "template.html" %}
{% load static %}
{% block title %}Mantenedor de contactos{% endblock %}
{% block content %}

{% if perms.Prueba_4.view_contacto %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Código</th>
        <th scope="col">Run</th>
        <th scope="col">Dv</th>
        <th scope="col">Nombres</th>
        <th scope="col">Apellido Paterno</th>
        <th scope="col">Apellido Materno</th>
        <th scope="col">Email</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Asunto</th>
      </tr>
    </thead>
    <tbody>
        {% for c in contactos %}
            <tr>
                <th scope="row">{{c.codigo}}</th>
                <td>{{c.run}}</td>
                <td>{{c.dv}}</td>
                <td>{{c.nombres}}</td>
                <td>{{c.apellido_paterno}}</td>
                <td>{{c.apellido_materno}}</td>
                <td>{{c.email}}</td>
                <td>{{c.telefono}}</td>
                <td>{{c.asunto}}</td>
                {% if perms.Prueba_4.delete_contacto %}
                <td><button type="button" class="btn btn-danger" 
                  data-bs-toggle="modal" 
                  data-bs-target="#mdl-{{c.codigo}}">ELIMINAR</button>
                  <div id="mdl-{{c.codigo}}" class="modal" tabindex="-1" >
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title">Advertencia</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">                            
                          </button>
                        </div>
                        <div class="modal-body">
                          <p>Se eliminará el registro seleccionado. ¿Desea Continuar?.</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                          <form method="GET" action="">
                            <input name="codigo" value="{{c.codigo}}" type="hidden" />
                            <button type="submit" class="btn btn-primary">Aceptar</button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
                {% endif %}
                {% if perms.Prueba_4.change_contacto %}
                <td>
                  <button type="button" class="btn btn-primary" 
                  data-bs-toggle="modal" 
                  data-bs-target="#mdl-update-{{c.codigo}}">ACTUALIZAR</button>
                  <div id="mdl-update-{{c.codigo}}" class="modal" tabindex="-1" >
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title">Actualizar Registro</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal"
                           aria-label="Close">                            
                          </button>
                        </div>  
                        <div class="modal-body">
                          <form id="frm-contacto" method="POST" action="">{% csrf_token %}
                            <div class="container" style="max-width:700px !important">
                              <input type="hidden" id="txt-id" name="codigo" value="{{c.codigo}}">
                              <div class="form-group row">
                                <div class="col-sm-9">
                                  <label for="txt-run" class="form-label">RUN</label>
                                  <input id="txt-run" name="run" value="{{c.run}}" disabled class="form-control" placeholder="RUN" />
                                </div>
                                <div class="col-sm-3">
                                  <label for="txt-dv" class="form-label">DV</label>
                                  <input id="txt-dv" name="dv" value="{{c.dv}}" disabled class="form-control" placeholder="DV" />
                                </div>
                              </div>
                              <div class="form-group row">
                                <div class="col-sm-6">
                                  <label for="txt-nombres" class="form-label">NOMBRES</label>
                                  <input id="txt-nombres" name="nombres" value="{{c.nombres}}" class="form-control" placeholder="NOMBRES" />        
                                </div>
                                <div class="col-sm-6">
                                  <label for="txt-apellido-paterno" class="form-label">APELLIDO PATERNO</label>
                                  <input id="txt-apellido-paterno" name="apellido_paterno" value="{{c.apellido_paterno}}" class="form-control" placeholder="APELLIDO PATERNO" />        
                                </div>   
                              </div>
                              <div class="form-group row">
                                <div class="col-sm-6">
                                  <label for="txt-apellido-materno" class="form-label">APELLIDO MATERNO</label>
                                  <input id="txt-apellido-materno" name="apellido_materno" value="{{c.apellido_materno}}" class="form-control" placeholder="APELLIDO MATERNO" />        
                                </div> 
                              </div>
                              <div class="form-group row">
                                <div class="col-sm-6">
                                  <label for="txt-email" class="form-label">EMAIL</label>
                                  <input id="txt-email" name="email" value="{{c.email}}" class="form-control" placeholder="EMAIL" />        
                                </div>       
                                <div class="col-sm-6">
                                  <label for="txt-telefono" class="form-label">TELÉFONO</label>
                                  <input id="txt-telefono" name="telefono" value="{{c.telefono}}" class="form-control" placeholder="TELÉFONO" />        
                                </div> 
                              </div>    
                              <div class="form-group row">
                                <div class="col-sm-12">
                                  <label for="txt-asunto" class="form-label">ASUNTO</label>
                                  <textarea id="txt-asunto" name="asunto" class="form-control">{{c.asunto}}</textarea>
                                </div> 
                              </div>
                              <div class="form-group row">        
                                <button type="submit" style="margin-top: 15px;" 
                                              class=" col-sm-3 btn btn-primary"
                                              >ENVIAR</button>
                            </div>         
                          </div>
                        </form>                                                       
                        </div>                      
                      </div>
                    </div>
                  </div>                  
                </td>
                {% endif %}                
            </tr>
        {% endfor %}      
    </tbody>
  </table>
  {% endif %}

{% endblock %}